# Generated by Django 3.2 on 2020-10-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice_ids',
            field=models.IntegerField(default=None),
        ),
    ]
