# Generated by Django 3.2 on 2020-10-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_answerchoices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerChoices',
            new_name='AnswerChoice',
        ),
    ]
